<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Reports\FacturaReport.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <PackageReference Include="PdfSharpCore" Version="1.3.65" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="AspNetCore.Reporting" Version="2.1.0" />
    <PackageReference Include="System.Security.Permissions" Version="6.0.0" />
  </ItemGroup>

</Project>
  